apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
data:
  .dockerconfigjson: ew0KICAgICJhdXRocyI6IHsNCiAgICAgICJwb3J0aWZvbGlvY3IuYXp1cmVjci5pbyI6IHsNCiAgICAgICAgInVzZXJuYW1lIjogIlBvcnRpZm9saW9jciIsDQogICAgICAgICJwYXNzd29yZCI6ICJnYktXZjN5aENPMUdHSXBxekZHZ25rZkVEcDV3bzZmbWNibnVaU1dtMWQrQUNSRE5GYVQxIiwNCiAgICAgICAgImVtYWlsIjogInBlZHJvcGluZ3VlbGxpQGhvdG1haWwuY29tIiwNCiAgICAgICAgImF1dGgiOiAiIg0KICAgICAgfQ0KICAgIH0NCiAgfQ==
type: kubernetes.io/dockerconfigjson