apiVersion: v1
kind: PersistentVolume
metadata:
  name: meu-pv
spec:
  capacity:
    storage: 5Gi  # Tamanho do armazenamento
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  # Modo de acesso ao volume (ReadWriteOnce, ReadOnlyMany, ReadWriteMany)
  persistentVolumeReclaimPolicy: Retain  # Política de reutilização do volume (Retain, Delete)
  storageClassName: manual  # Nome da classe de armazenamento
  hostPath:
    path: /data/my-pv  # Caminho no host onde os dados serão armazenados
